name: Build-Vulkan-SDK-ARM

env:
  DEFAULT_VULKAN_SDK_VERSION: '1.4.321.1'

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Vulkan SDK version (e.g., 1.4.321.1)'
        required: false

jobs:
  build-linux-arm:
    name: Build Vulkan-SDK-ARM for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04-arm ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set version variable
        id: vars
        run: |
          VERSION=${{ github.event.inputs.version || env.DEFAULT_VULKAN_SDK_VERSION }}
          echo "SDK_URL=https://sdk.lunarg.com/sdk/download/${VERSION}/linux/vulkansdk-linux-arm64-${VERSION}.tar.xz" >> $GITHUB_ENV
          echo "Using specified SDK version: ${VERSION}"

      - name: Update APT
        run: sudo apt update

      - name: Install Host Dependencies
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-22.04-arm" ]]; then
            sudo apt install cmake ninja-build gcc-12 g++-12 bison ocaml-core xz-utils pkg-config python3-pip -y
          elif [[ "${{ matrix.os }}" == "ubuntu-24.04-arm" ]]; then
            sudo apt install cmake ninja-build gcc-14 g++-14 bison ocaml-core xz-utils pkg-config python3-pip -y
          fi

      - name: Install Python
        run: pip3 install setuptools wheel

      - name: Install Target Dependencies
        run: |
          sudo apt install libglm-dev libxcb-dri3-0 libxcb-present0 libpciaccess0 \
          libpng-dev libxcb-keysyms1-dev libxcb-dri3-dev libx11-dev \
          libwayland-dev libxrandr-dev libxcb-randr0-dev libxcb-ewmh-dev \
          libx11-xcb-dev liblz4-dev libzstd-dev \
          libxml2-dev wayland-protocols -y --no-install-recommends

      - name: Download SDK
        run: curl -L -o vulkan-sdk.tar.xz "$SDK_URL"

      - name: Extract SDK and Determine SDK Directory
        run: |
          tar -xf vulkan-sdk.tar.xz
          SDK_DIR=$(find . -maxdepth 1 -type d -name '1.*' | head -n 1)
          echo "SDK_DIR=${SDK_DIR}" >> $GITHUB_ENV
          echo "SDK_VERSION=$(basename ${SDK_DIR})" >> $GITHUB_ENV

      - name: Remove x86_64 directory
        run: |
          cd "${{ env.SDK_DIR }}"
          rm -rf x86_64

      - name: Build SDK
        run: |
          cd "${{ env.SDK_DIR }}"
          if [[ "${{ matrix.os }}" == "ubuntu-22.04-arm" ]]; then
            CC=/usr/bin/gcc-12 CXX=/usr/bin/g++-12  ./vulkansdk --maxjobs vulkan-loader vulkan-validationlayers vulkan-extensionlayer
          elif [[ "${{ matrix.os }}" == "ubuntu-24.04-arm" ]]; then
            CC=/usr/bin/gcc-14 CXX=/usr/bin/g++-14  ./vulkansdk --maxjobs vulkan-loader vulkan-validationlayers vulkan-extensionlayer
          fi

      # When an Artifact is uploaded, all the files are assembled into an immutable Zip archive. There is currently no way to download artifacts in a format other than a Zip or to download individual artifact contents.
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vulkansdk-linux-arm64-${{ matrix.os }}-${{ env.SDK_VERSION }}
          path: ${{ env.SDK_VERSION }}

  release:
    name: Publish release
    runs-on: ubuntu-22.04
    needs: build-linux-arm
    permissions:
      contents: write
    steps:
      - name: Download all assets
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: List assets
        run: ls -R dist

      - name: Set tag name
        id: set_tag
        run: |
          # Get current date/time in UTC, format YYYYMMDDHHMM
          DATE=$(date -u +'%Y%m%d%H%M')
          VERSION="${{ github.event.inputs.version || env.DEFAULT_VULKAN_SDK_VERSION }}"
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "tag=${VERSION}-${DATE}" >> $GITHUB_OUTPUT
          else
            PR_BRANCH="${{ github.head_ref }}"
            PR_BRANCH_CLEAN=$(echo "$PR_BRANCH" | tr '/' '-' | tr -cd '[:alnum:]-')
            echo "tag=${VERSION}-${PR_BRANCH_CLEAN}-${DATE}" >> $GITHUB_OUTPUT
          fi

      - name: Set prerelease flag
        id: set_prerelease
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "is_prerelease=false" >> $GITHUB_OUTPUT
          else
            echo "is_prerelease=true" >> $GITHUB_OUTPUT
          fi

      - name: Create/Update release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.set_tag.outputs.tag }}
          prerelease: ${{ steps.set_prerelease.outputs.is_prerelease }}
          name: ${{ steps.set_tag.outputs.tag }}
          body: |
            Blah blah
            Tag: ${{ steps.set_tag.outputs.tag }}
          files: |
            dist/**
